### ISSUE TITLE
Feature request: option to choose command to run to shutdown

### ISSUE THREAD

**Issue by dattas** [wilriker/execonmcode#1]
I'd like to customize the shutdown procedure instead of using just the poweroff command. A `-shutdownCommand` which defaults to `poweroff` I think would be a great addition and allow me to use the release version instead of having to compile this myself, and I'd imagine others could use it as well.

Thank you for your consideration!

**Comment by wilriker** [comment]
To be honest, I saw that one coming. :joy: 

I'll look into that and provide an update early next week latest.

**Comment by wilriker** [comment]
And it's done. The command to execute is now available via `-command <string>` (enclose it in quotes if parameters are need to be passed) and I thus renamed the project to `execonmcode`.
