### ISSUE TITLE
Program is successfully running, but M7722 doesn't trigger shutdown

### ISSUE THREAD

**Issue by Ohmarinus** [wilriker/execonmcode#5]
Hello, I managed to get it all running successfully as a system service, after a reboot I checked the status, but it doesn't shutdown after sending an M7722 through the Duet webpanel.

This is the systemctl status update:
```
pi@duet3:~ $ sudo systemctl status shutdownsbc.service
● shutdownsbc.service - Duet API listener to shutdown the SBC
   Loaded: loaded (/etc/systemd/system/shutdownsbc.service; enabled; vendor preset: enabled)
   Active: activating (auto-restart) (Result: exit-code) since Sat 2021-02-06 13:05:18 CET; 6s ago
  Process: 1372 ExecStart=/usr/local/bin/execonmcode -mCode 7722 -command poweroff (code=exited, status=203/EXEC)
 Main PID: 1372 (code=exited, status=203/EXEC)

Feb 06 13:05:18 duet3 systemd[1]: shutdownsbc.service: Main process exited, code=exited, status=203/EXEC
Feb 06 13:05:18 duet3 systemd[1]: shutdownsbc.service: Failed with result 'exit-code'.

```

Any idea what could be wrong?

**Comment by wilriker** [comment]
The output of `systemctl status` states that the application is not running. 
Please try running
```
sudo /usr/local/bin/execonmcode -mCode 7722 -command poweroff
```
from command-line and see if it outputs any error. You can also amend `-debug` and/or `-trace` to get more details of what's going on.
Also please make sure that the binary you downloaded matches your system architecture, i.e. ARM 32bit or 64bit.

**Comment by Ohmarinus** [comment]
I think I've discovered the problem (sorry for my late reply, just got around to try and fix this).

When I install everything it works well (https://www.youtube.com/watch?v=WxcLDUF9zMs)

But after I boot up the Pi again, the 'execonmcode' disappears again from /usr/local/bin/

This is really strange, as the data does exist right after installing. It simply disappears again when I reboot the Pi.

Any idea what could cause this? Right after installing using M7722 through the DWC of Duet works well. So it's the disappearing of the files that is causing the issue. I have tried both binaries.

**Comment by wilriker** [comment]
> But after I boot up the Pi again, the 'execonmcode' disappears again from /usr/local/bin/

Now, this is strange and certainly something that is not caused by `execonmcode` (why would it delete itself? ;-) ).
There are a few things I can think of but not sure if they apply to you:
* Is your `/usr/local/bin` mounted as `tmpfs`? (You can find out by running `mount` and see if this directory or any of its parents is mounted as `type tmpfs`)
* Is `/usr/loca/bin` a symlink pointing to e.g. `/tmp`? (You can find out by running `ls -ld /usr/local/bin` if it lists an arrow pointing to somewhere you need to check if that destination is mounted on tmpfs)
* Is your `/` mounted read-only? (`mount` will tell you in the part in parentheses, it will state `rw` for read-write and `ro` for read-only) If that's the case I wonder why it would be possible to copy anything there unless there is any kind of `overlayfs` running.

This is getting deep down into Linux filesystem internals.

**Comment by Ohmarinus** [comment]
Sadly none of your suggestions seem to have given any hint of what could be going on. It all seems to be in correct working order. Also, the SD card is fine, I can read and write to it without problems.

I'll try to install it for a third time.. (and document my process).

Don't mind the 'execonmode' file, it was my error from an earlier attempt and I don't know how to remove it/was too lazy to look up how to remove the file. Strange thing is that the 'execonmode' file does stay in there, but the 'execonmcode' file doesn't....

Step 1:
Files are in the right place
![execon1](https://user-images.githubusercontent.com/5002107/111154338-69675b00-8593-11eb-8017-2df418bb6c6d.jpg)

Step 2:
Service was running and Pi shutdown after sending M7722 in the DWC
![execon2](https://user-images.githubusercontent.com/5002107/111154361-6ff5d280-8593-11eb-9911-9a7b736965ff.jpg)

Step 3:
After starting the Pi again, I check the /usr/local/bin/ folder and poof it's gone again
![execon3](https://user-images.githubusercontent.com/5002107/111154377-73895980-8593-11eb-882c-5eaa7b705b50.jpg)

To add, I also have the service running fine before restarting the Pi. The issue simply persist that when I start it up again, the files are gone:
![execon4](https://user-images.githubusercontent.com/5002107/111155941-6bcab480-8595-11eb-845d-83b56358e4ea.jpg)

To add one more thing (sorry) I removed the 'execonmode' file, but after rebooting the Pi, this old file was back on the SD card as well. There must be an issue somewhere...

**Comment by Ohmarinus** [comment]
Small update, decided to do a fresh install on a new SD card, but now it's throwing this error when installing the service through systemctl:
pi@duet3:/etc/systemd/system $ sudo systemctl start shutdownsbc.service
A dependency job for shutdownsbc.service failed. See 'journalctl -xe' for details.

Sadly journalctl -xe doesn't tell what's going on.

Restarting didn't improve the situation.

The execonmcode also doesn't want to run by itself:
![nocon](https://user-images.githubusercontent.com/5002107/111167971-e994bd00-85a1-11eb-8cef-0da957604c46.jpg)

**Comment by wilriker** [comment]
Is DCS running? It won't work if DCS is not started. You can also try using
```
-socketPath /run/dsf/dcs.sock
```
as officially `/var/run` is deprecated and should be replaced by just `/run`

**Comment by Ohmarinus** [comment]
> 
> 
> Is DCS running? It won't work if DCS is not started. You can also try using
> 
> ```
> -socketPath /run/dsf/dcs.sock
> ```
> 
> as officially `/var/run` is deprecated and should be replaced by just `/run`

All fixed. So using a differend MicroSD card fixed it for me, and additionally connecting the Pi up to the controller. Thanks for your help, and I'm sorry it was the SD card.. Well, good to know anyway, maybe this will be useful to someone else having the same problem.

Thanks a lot for your helpful addon! :)
