### ISSUE TITLE
Incompatible API version with v5.2.0 and DSF 3.4.0

### ISSUE THREAD

**Issue by adammhaile** [wilriker/execonmcode#6]
I'm running DSF 3.4.0 on a Pi 4 and the latest (v5.2.0) execonmcode and getting the following error any time I try to run it:

`Incompatible API version (expected 10 got 0)`

I noticed that you are pulling go modules from here: https://github.com/Duet3D/DSF-APIs/
But that has been deprecated for here: https://github.com/Duet3D/dsf-go
Maybe that is part of the issue.
Though, also the last release of execonmcode is over a year old so maybe it's just that it's incompatible with the latest Duet 3.4.0 release?
Edit: they haven't updated dsf-go in the same time period.... :( 

Any suggestions would be appreciated. I'd love to use this for my machine.

Thanks!

**Comment by wilriker** [comment]
Hi @adammhaile ,

as you realized yourself, https://github.com/Duet3D/dsf-go has not been maintained anymore and even is archived by now so there is no more development possible.

This leads to the unfortunate situation that I cannot update `execonmcode` unless I also update the Go libs which I do not have time anymore.

So unless something magical happens I cannot do anything about the incompatibility.

To be fair, the Go library started as a pet project of mine and I was probably the only one using it. So when I dropped out of Duet3D there was no expertise or incentive left to keep up development.

I'm sorry.

**Comment by adammhaile** [comment]
Oh damn - I didn't noticed it was archived too. That's sad... wish Duet would keep up with their own APIs :( 
Thanks!

**Comment by wilriker** [comment]
@adammhaile AFAICT they do keep their Python library up to date. It should not be too hard to port my Go code over to Python. Only i don't have the time and never seen myself as a Pythonic. But maybe someone in the forum can do that.

EDIT: if someone actually provides a Python based solution, please post here.

**Comment by wilriker** [comment]
Python-based version: https://forum.duet3d.com/topic/29783
